FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

# Add PostgreSQL official repo (to get pg_dump v17)
RUN apt-get update && \
    apt-get install -y wget gnupg && \
    echo "deb http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" > /etc/apt/sources.list.d/pgdg.list && \
    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /etc/apt/trusted.gpg.d/pgdg.gpg && \
    apt-get update && \
    apt-get install -y \
      curl \
      wget \
      unzip \
      gzip \
      postgresql-client-17 \
      default-mysql-client && \
    wget -qO - https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2204-x86_64-100.9.4.tgz | tar -xz && \
    mv mongodb-database-tools-ubuntu2204-x86_64-100.9.4/bin/* /usr/local/bin/ && \
    curl -s https://rclone.org/install.sh | bash && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENTRYPOINT ["/bin/bash", "/common/backup.sh"]
